name: flutterauth
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  flutter_svg: ^0.19.1
 # http: ^0.13.3
  firebase_core: any
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  #cloud_firestore: ^0.13.6
  firebase_database: any
  firebase_performance: any

  flutter_settings_screens: ^0.2.2+1
  #provider: ^5.0.0
  validators: any
  google_sign_in: ^4.5.6
  dropdown_search: ^0.4.8
  intl: ^0.16.1
  charts_flutter: any
  font_awesome_flutter: ^9.1.0
  firebase_storage: any
  #date_field: ^0.3.3
  fzregex: ^1.0.3
  flare_flutter: ^2.0.6
  randomizer: ^0.0.2
  flrx_validator: ^0.4.0+2
  mailer: any
  fluttertoast: ^8.0.8
  date_time_picker: any
  #file_picker: ^2.1.5+1
  flutter_document_picker: ^4.0.0
  pdf_viewer_plugin: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
  flutter_lints: ^1.0.0
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - images/slides/1.png
    - images/slides/2.jpg
    - images/slides/3.jpg
    - images/slides/4.jpg
    - images/slides/etudiant.jpg
    - images/slides/admin.jpg
    - images/slides/parent.jpg
    - images/slides/enseig.png
    - images/slides/s1.jpg
    - images/slides/s2.jpg
    - images/slides/s3.jpg
    - images/slides/s4.jpg
    - images/slides/main_top.png
    - images/slides/main_button.jpg
    - assets/

  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
